name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  UNIT: dev.narumi.bot
  WORKDIR: /Users/narumi/services/bot
  PLIST_DIR: /Users/narumi/Library/LaunchAgents

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Stop and disable service
        continue-on-error: true
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl stop ${{ env.UNIT }}
          launchctl unload bot.plist
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv sync
          uv run playwright install chromium
      - name: Create dotenv
        run: |
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo BOT_WHITELIST=${{ vars.BOT_WHITELIST }} >> .env
          echo OPENAI_MODEL=${{ vars.OPENAI_MODEL }} >> .env
          echo OPENAI_API_VERSION=${{ vars.OPENAI_API_VERSION }} >> .env
          echo DEVELOPER_CHAT_ID=${{ vars.DEVELOPER_CHAT_ID }} >> .env
          echo AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} >> .env
          echo AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} >> .env
          echo LOGFIRE_TOKEN=${{ secrets.LOGFIRE_TOKEN }} >> .env
      - name: Copy files
        run: |
          rm -rf ${{ env.WORKDIR }}
          cp -rf ${{ github.workspace }} ${{ env.WORKDIR }}
          cp bot.plist ${{ env.PLIST_DIR }}
      - name: Start service
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl load -w bot.plist
          launchctl start ${{ env.UNIT }}
